site_name: demoMD
site_author: Leonardo furtado Kauffmann

nav:
  - Home: index.md
  - titulos: headings.md
  - paragrafos e enfatização: paragraphs.md
  - citações: blockquotes.md
  - URLS, links e imagens: links.md

theme:
  name: material
