site_name: demoMD
site_author: Leonardo furtado Kauffmann

nav:
  - titulos: headings.md
  - paragrafos e enfatização: paragraphs.md
  - citações: blockquotes.md
  - URLS e links: links.md

theme:
  name: material
